Update README.md
AY2425S1-CS2103T-W12-3/tp pull request #41
Opened 2024-10-01 15:51 UTC by SlothyCat

2024-10-02 06:19 UTC, jtooya commented
Please create PR from add-photo branch 🙏

2024-10-03 08:13 UTC, kimberlytmq approved these changes, later dismissed
lgtm!

2024-10-03 10:38 UTC, jtooya requested changes

2024-10-03 10:38 UTC, jtooya commented on README.md
> +* It is named `UniLink` because we want to link University Students up to enjoy a better student life! :3
Perhaps we can consider changing the wording from enjoy a better student life to something more specific, like "manage contacts, professional and otherwise, easier"

2024-10-03 10:38 UTC, jtooya commented on README.md
> +* The project simulates an ongoing software project for a desktop application (called _UniLink_) used for managing contact details of a University student.
Maybe dumb question but are we still simulating an ongoing software project, if this is actually an ongoing software project? Maybe we should delete the line?

2024-10-05 15:43 UTC, kimberlytmq approved these changes
lgtm!

2024-10-05 15:47 UTC, jtooya approved these changes
lgtm

2024-10-05 15:48 UTC, merged